---
- name: Enabling k8s ports firewalld
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  loop: "{{ k8s_fw_port }}"

- name: Reloading FW
  systemd:
    name: firewalld
    state: reloaded

- name: Configuring kubeadm
  shell: kubeadm config images pull 

- name: Allowing acces from worker1      
  firewalld:
    rich_rule: rule family=ipv4 source address={{ workerip }} accept
    permanent: yes
    state: enabled

- name: Allowing acces from worker2
  firewalld:
    rich_rule: rule family=ipv4 source address={{ workerip2 }} accept
    permanent: yes
    state: enabled    

- name: Reloading FW
  systemd:
    name: firewalld
    state: reloaded

- name: Initializing K8s cluster
  shell: kubeadm init --pod-network-cidr 10.0.2.0/24
  ignore_errors: yes

- name: Ensuring .kube dir exists
  file:
    path: /home/ansible/.kube
    state: directory

- name: Configuring users cluster access
  become: yes
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/ansible/.kube/config
    remote_src: yes
    owner: ansible
    group: ansible

- name: Kubeconfig for user ansible
  shell: export KUBECONFIG=$HOME/.kube/config  

- name: Setting k8s join command as variable
  become_user: ansible
  shell: kubeadm token create --print-join-command
  register: k8s_join_command
 
- name: Setting k8s_join_token to local file
  become: false
  local_action: copy content="{{ k8s_join_command.stdout_lines[0] }}" dest="roles/workers/files/k8s_join_command.sh"

... 
