---
- name: Enable k8s ports firewalld
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  loop: "{{ k8s_fw_port }}"

- name: Reload FW
  systemd:
    name: firewalld
    state: reloaded

- name: Configure kubeadm
  shell: kubeadm config images pull 

- name: Allow acces from worker1      
  firewalld:
    rich_rule: rule family=ipv4 source address={{ workerip }} accept
    permanent: yes
    state: enabled

- name: Reload FW
  systemd:
    name: firewalld
    state: reloaded

- name: Initializing K8s cluster
  shell: kubeadm init --pod-network-cidr 192.169.0.0/16
  ignore_errors: yes

- name: Ensure .kube dir exists
  file:
    path: /home/ansible/.kube
    state: directory

- name: Configuring users cluster access
  become: yes
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/ansible/.kube/config
    remote_src: yes
    owner: ansible
    group: ansible

- name: Kubeconfig for user ansible
  shell: export KUBECONFIG=$HOME/.kube/config  

- name: Setting k8s join command as variable
  become_user: ansible
  shell: kubeadm token create --print-join-command
  register: k8s_join_token
 
- name: Setting k8s_join_token as fact
  set_fact:
    k8s_join_token: "{{ k8s_join_token.stdout_lines[0] }}"

... 
