---
- name: Enable k8s ports firewalld
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  loop: "{{ k8s_fw_port }}"

- name: Reload FW
  systemd:
    name: firewalld
    state: reloaded

- name: Configure kubeadm
  shell: kubeadm config images pull

- name: Allow acces from worker1
  firewalld:
    rich_rule: rule family=ipv4 source address={{ workerip }} accept
    permanent: yes
    state: enabled

- name: Reload FW
  systemd:
    name: firewalld
    state: reloaded

- name: Install CNI and store join token into a var
  shell: kubeadm init --pod-network-cidr 192.169.0.0/16
  register: join_token
  ignore_errors: yes

- name: Copy join_token to a join_token.txt in files
  copy:
    content: "{{ join_token.stdout }}"
    dest: "{{k8s_join_out}}"
    force: yes

- name: Export variable kubeconfig
  shell: export KUBECONFIG=/etc/kubernetes/admin.conf

- name: Create kube directory for root user
  file:
    path: /root/.kube
    owner: $(id -u)
    group: $(id -g)
    mode: '0644'  

- name: Copy content k8s config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
...
