---
- name: Install NFS server packages
  dnf: 
    name: "{{ nfs_pkg }}"
    state: present

- name: Enable nfs-server service
  systemd:
    name: nfs-server
    state: started
    enabled: yes

- name: Create NFS Export directory
  file:
    path: /srv/nfs
    state: directory

- name: Create MySQL1 NFS directory
  file:
    path: /srv/nfs/mysql1
    state: directory

- name: Create MySQL2 NFS directory
  file:
    path: /srv/nfs/mysql2
    state: directory

- name: Create MySQL3 NFS directory
  file:
    path: /srv/nfs/mysql3
    state: directory

- name: Copy export values
  blockinfile:
    path: /etc/exports
    block: |
      # master
      /srv/nfs	{{ masterip }}(rw,sync,no_root_squash) 
      # worker01
      /srv/nfs	{{ workerip }}(rw,sync,no_root_squash)
      # worker02
      /srv/nfs	{{ workerip2 }}(rw,sync,no_root_squash) 

- name: Re-export the sare
  command: exportfs -r

- name: Enable services firewalld
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
  loop: "{{ nfs_fw_svc }}"

- name: Reload FW
  systemd:
    name: firewalld
    state: reloaded
...
