---
- name: Install pre-deploy common packages
  dnf: 
    name: "{{ prev_pkg }}"
    state: present

- name: Set timezone to Europe/Madrid
  timezone:
    name: Europe/Madrid

- name: Enable chrony service
  systemd:
    name: chronyd
    state: started
    enabled: yes
- name: Set ntp timedate  
  command: timedatectl set-ntp true

- name: Disable SELinux
  replace:
    path: /etc/selinux/config
    regexp: enforcing
    replace: disabled
...
