---

- name: Installing pre-deploy common packages
  dnf: 
    name: "{{ prev_pkg }}"
    state: present

- name: Seting timezone to Europe/Madrid
  timezone:
    name: Europe/Madrid

- name: Enabling chrony service
  systemd:
    name: chronyd
    state: started
    enabled: yes
- name: Seting ntp timedate  
  command: timedatectl set-ntp true

- name: Disabling SELinux
  replace:
    path: /etc/selinux/config
    regexp: enforcing
    replace: disabled
...
