---
- name: Copying Hosts values
  blockinfile:
    path: /etc/hosts
    block: |
      127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
      ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
      {{ masterip }}      ansk8master
      {{ workerip }}      ansk8worker
      {{ masterip }}      nfs

- name: Enabling FW
  systemd:
    name: firewalld
    state: started

- name: Enabling br_netfilter
  modprobe:
    name: br_netfilter
    state: present

- name: FW permanent masquerade  
  firewalld:
    masquerade: yes
    permanent: true
    state: enabled

- name: Copying k8s.conf for sysctl.d
  blockinfile:
    path: /etc/sysctl.d/k8s.conf
    block: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables  = 1
      net.ipv4.ip_forward                 = 1
    create: true

- name: Disabling SWAP
  command: swapoff -a

- name: Removing SWAP from /etc/fstab
  lineinfile:
    path: /etc/fstab
    regexp: "swap"
    state: absent

- name: WGET CRI-O repo 1
  get_url: 
    url: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_8_Stream/devel:kubic:libcontainers:stable.repo 
    dest: /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo
    validate_certs: false

- name: WGET CRI-O repo 2
  get_url: 
    url: https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:1.23:1.23.1/CentOS_8_Stream/devel:kubic:libcontainers:stable:cri-o:1.23:1.23.1.repo
    dest: /etc/yum.repos.d/devel:kubic:libcontainers:stable:cri-o:1.23:1.23.1.repo
    validate_certs: false

- name: Installing CRI-O
  dnf: 
    name: cri-o
    state: present
    disable_gpg_check: yes

- name: Enabling CRI-O service
  systemd:
    name: crio
    state: started
    enabled: yes

- name: Configuring k8s repo
  blockinfile:
    path: /etc/yum.repos.d/kubernetes.repo
    block: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    create: true    

- name: Installing k8s packages
  dnf: 
    name: "{{ k8s_pkg }}"
    state: present        

- name: Enabling Kubelet
  systemd:
    name: kubelet
    state: started
    enabled: yes
...
