---
prev_pkg: ['chrony', 'nfs-utils', 'wget', 'nfs4-acl-tools']
nfs_pkg: ['nfs-utils', 'net-tools']
masterip: 40.118.41.26
workerip: 104.214.232.46
workerip2: 40.118.41.61
nfs_fw_svc: ['nfs', 'rpc-bind', 'mountd']
k8s_pkg: ['kubelet', 'kubeadm', 'kubectl']
k8s_fw_port: ['6443/tcp', '2379-2380/tcp', '10250-10252/tcp', '10255/tcp']
workers_fw_port: ['10250/tcp', '30000/tcp', '32767/tcp']
...
