---
- name: Enabling workers ports firewalld
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  loop: "{{ workers_fw_port }}"

- name: Reload FW
  systemd:
    name: firewalld
    state: reloaded

- name: Copy k8s join command to local
  copy:
    src: roles/workers/files/k8s_join_command.sh
    dest: /tmp/k8s_join_command.sh
    owner: ansible
    group: ansible

- name: Join node to k8s cluster
  command: sh /tmp/k8s_join_command.sh
...
