---
- name: Enabling workers ports firewalld
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  loop: "{{ workers_fw_port }}"

- name: Reloading FW
  systemd:
    name: firewalld
    state: reloaded

- name: Copying k8s join command to local
  copy:
    src: roles/workers/files/k8s_join_command.sh
    dest: /tmp/k8s_join_command.sh
    owner: ansible
    group: ansible

- name: Joining node to k8s cluster
  command: sh /tmp/k8s_join_command.sh
  register: join_debug

- name: Debugging k8s worker join
  debug:
    var: join_debug
...
