---

- name: First common features configuration
  hosts: all
  vars_files:
    - "../vars/allvars.yml"
  gather_facts: false
  tasks:
    - include_role:
        name: common
        tasks_from: 01_previous_config.yml

- name: NFS server install & config
  hosts: nfs
  vars_files:
    - "../vars/allvars.yml"
  roles:
    - nfs

- name: K8s common features configuration
  hosts: all
  vars_files:
    - "../vars/allvars.yml"
  gather_facts: false
  tasks:
    - include_role:
        name: common
        tasks_from: 02_k8s_common_config.yml

- name: K8s master configuration
  hosts: master
  vars_files:
    - "../vars/allvars.yml"
  roles:
    - master

- name: K8s worker joining configuration
  hosts: workers
  vars_files:
    - "../vars/allvars.yml"
  roles:
    - workers      
...
