apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql-0
  namespace: percona-app
  labels:
    app: mysql
    podindex: "0"
  annotations:
    volume.beta.kubernetes.io/storage-class: ""
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /srv/nfs/mysql1
    server: 10.0.1.10
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql-1
  namespace: percona-app
  labels:
    app: mysql
    podindex: "1"
  annotations:
    volume.beta.kubernetes.io/storage-class: ""
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /srv/nfs/mysql2
    server: 10.0.1.10
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mysql-0
  namespace: percona-app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: mysql
      podindex: "0"
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mysql-1
  namespace: percona-app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: mysql
      podindex: "1"
