apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume-1
  namespace: percona-app
  labels:
    app: mysql
    podindex: "1"
  annotations:
    volume.beta.kubernetes.io/storage-class: ""
spec:
  capacity:
    storage: 24Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /srv/nfs/mysql1
    server: 10.0.1.10
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume-2
  namespace: percona-app
  labels:
    app: mysql
    podindex: "2"
  annotations:
    volume.beta.kubernetes.io/storage-class: ""
spec:
  capacity:
    storage: 24Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /srv/nfs/mysql2
    server: 10.0.1.10
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim-1
  namespace: percona-app
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  selector:
    matchLabels:
      app: mysql
      podindex: "1"
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim-2
  namespace: percona-app
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  selector:
    matchLabels:
      app: mysql
      podindex: "2"
